#include "latencies_float.h"

void test_float_latencies() {
    CALL_TESTS_FLOAT(SIMD1_32f);
    CALL_TESTS_FLOAT(SIMD2_32f);
    CALL_TESTS_FLOAT(SIMD4_32f);
    CALL_TESTS_FLOAT(SIMD8_32f);
    CALL_TESTS_FLOAT(SIMD16_32f);
    CALL_TESTS_FLOAT(SIMD32_32f);

    CALL_TESTS_FLOAT(SIMD1_64f);
    CALL_TESTS_FLOAT(SIMD2_64f);
    CALL_TESTS_FLOAT(SIMD4_64f);
    CALL_TESTS_FLOAT(SIMD8_64f);
    CALL_TESTS_FLOAT(SIMD16_64f);
}