#include "latencies_int.h"

void test_int_latencies() {
    CALL_TESTS_INT(SIMD1_8i);
    CALL_TESTS_INT(SIMD2_8i);
    CALL_TESTS_INT(SIMD4_8i);
    CALL_TESTS_INT(SIMD8_8i);
    CALL_TESTS_INT(SIMD16_8i);
    CALL_TESTS_INT(SIMD32_8i);
    CALL_TESTS_INT(SIMD64_8i);
    CALL_TESTS_INT(SIMD128_8i);

    CALL_TESTS_INT(SIMD1_16i);
    CALL_TESTS_INT(SIMD2_16i);
    CALL_TESTS_INT(SIMD4_16i);
    CALL_TESTS_INT(SIMD8_16i);
    CALL_TESTS_INT(SIMD16_16i);
    CALL_TESTS_INT(SIMD32_16i);
    CALL_TESTS_INT(SIMD64_16i);

    CALL_TESTS_INT(SIMD1_32i);
    CALL_TESTS_INT(SIMD2_32i);
    CALL_TESTS_INT(SIMD4_32i);
    CALL_TESTS_INT(SIMD8_32i);
    CALL_TESTS_INT(SIMD16_32i);
    CALL_TESTS_INT(SIMD32_32i);

    CALL_TESTS_INT(SIMD1_64i);
    CALL_TESTS_INT(SIMD2_64i);
    CALL_TESTS_INT(SIMD4_64i);
    CALL_TESTS_INT(SIMD8_64i);
    CALL_TESTS_INT(SIMD16_64i);
}
