#include "latencies_uint.h"

void test_uint_latencies() {
    CALL_TESTS_UINT(SIMD1_8u);
    CALL_TESTS_UINT(SIMD2_8u);
    CALL_TESTS_UINT(SIMD4_8u);
    CALL_TESTS_UINT(SIMD8_8u);
    CALL_TESTS_UINT(SIMD16_8u);
    CALL_TESTS_UINT(SIMD32_8u);
    CALL_TESTS_UINT(SIMD64_8u);
    CALL_TESTS_UINT(SIMD128_8u);

    CALL_TESTS_UINT(SIMD1_16u);
    CALL_TESTS_UINT(SIMD2_16u);
    CALL_TESTS_UINT(SIMD4_16u);
    CALL_TESTS_UINT(SIMD8_16u);
    CALL_TESTS_UINT(SIMD16_16u);
    CALL_TESTS_UINT(SIMD32_16u);
    CALL_TESTS_UINT(SIMD64_16u);

    CALL_TESTS_UINT(SIMD1_32u);
    CALL_TESTS_UINT(SIMD2_32u);
    CALL_TESTS_UINT(SIMD4_32u);
    CALL_TESTS_UINT(SIMD8_32u);
    CALL_TESTS_UINT(SIMD16_32u);
    CALL_TESTS_UINT(SIMD32_32u);

    CALL_TESTS_UINT(SIMD1_64u);
    CALL_TESTS_UINT(SIMD2_64u);
    CALL_TESTS_UINT(SIMD4_64u);
    CALL_TESTS_UINT(SIMD8_64u);
    CALL_TESTS_UINT(SIMD16_64u);
}